import Topbar from "../Topbar";
import Navbar from "../Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useEffect, useState } from "react";

export const metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [key, setKey] = useState<string>("");
  const [accessGranted, setAccessGranted] = useState<boolean>(false);
  const [accessError, setAccessError] = useState<string>("");
  const handleSubmitPrivateKey = (e: any) => {
    e.preventDefault();
    setAccessError("");
    if (key === "poddapp@123") {
      setAccessGranted(true);
      localStorage.setItem("accessKey", key);
    } else {
      setAccessError("Access Denied! Incorrect Key.");
    }
  };

  useEffect(() => {
    const accessKey = localStorage.getItem("accessKey");
    if (accessKey !== null && accessKey === "poddapp@123") {
      setAccessGranted(true);
    }
  }, []);

  return accessGranted ? (
    <div className="main-wrapper">
      <Topbar />
      <div className="h-full flex flex-1 pt-[54px] lg:pt-[96px]">
        {/* <Navbar /> */}
        {children}
      </div>
      <ToastContainer />
    </div>
  ) : (
    <form onSubmit={handleSubmitPrivateKey}>
      <div className="lock-wrapper">
        <p>ENTER PRIVATE ACCESS KEY!</p>
        {accessError && <p className="access-error">{accessError}</p>}
        <div
          tabIndex={0}
          className="dropdown-content z-[1] menu px-[50px] py-5 shadow bg-custom-lightgraythree rounded-box w-[610px] flex flex-row gap-4 items-center"
        >
          <input
            type="password"
            placeholder="type here.."
            className="flex-1 bg-black border input border-custom-border text-custom-gray"
            value={key}
            onChange={(e) => setKey(e.target.value)}
            required
          />
        </div>
        <button
          className="btn hover:bg-custom-default border-custom-default hover:border-custom-default"
          type="submit"
        >
          Submit
        </button>
      </div>
    </form>
  );
}
